version: '2'

build:
  context: .
  args:
    - KODEXPLORER_VERSION=4.39

services:
  kodexplorer:
    image: xaljer/kodexplorer
    restart: always
    ports:
      - '5001:80'
    volumes:
      - '/srv/docker/kodexplorer-data:/var/www/html'
